language: python
python: 3.5
env:
  # Avoid testing pypy on travis until the following issue is fixed:
  #   https://github.com/travis-ci/travis-ci/issues/4756
  # - TOX_ENV=pypy
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py27
  - TOX_ENV=docs
install:
  - pip install coveralls tox
script: tox -e $TOX_ENV
after_success: coveralls
