language: python
python:
  # Avoid testing pypy on travis until the following issue is fixed:
  #   https://github.com/travis-ci/travis-ci/issues/4756
  # - pypy
  - 3.6
  - 3.5
  - 3.4
  - 2.7
install:
  - pip install coveralls tox-travis
script: tox
after_success: coveralls
